export const RECEIVE_QUAN_LIST = 'RECEIVE_QUAN_LIST';
export const SET_QUAN_LIST_CURRENT_PAGE = 'SET_QUAN_LIST_CURRENT_PAGE';
export const SET_QUAN_SEARCH_CRITERIA = 'SET_QUAN_SEARCH_CRITERIA';
export const SET_QUAN_STATUS = 'SET_QUAN_STATUS';
export const SHOW_CANCEL_QUAN_MODAL = 'SHOW_CANCEL_QUAN_MODAL';
export const HIDE_CANCEL_QUAN_MODAL = 'HIDE_CANCEL_QUAN_MODAL';
