export const DELETE_QUAN_BATCH_CREATION_DISPATCH_PRODUCT_LIMIT = 'DELETE_QUAN_BATCH_CREATION_DISPATCH_PRODUCT_LIMIT';
export const ADD_QUAN_BATCH_CREATION_DISPATCH_PRODUCT_LIMIT = 'ADD_QUAN_BATCH_CREATION_DISPATCH_PRODUCT_LIMIT';
export const SET_PER_USER_LIMIT = 'SET_PER_USER_LIMIT';
export const SET_IS_AUTO_ONLINE = 'SET_IS_AUTO_ONLINE';
export const SET_DISCOUNT_TYPE = 'SET_DISCOUNT_TYPE';
export const SET_PLATEFORM_LIMIT_LIST = 'SET_PLATEFORM_LIMIT_LIST';
export const SET_APPLY_PRODUCT_TYPE = 'SET_APPLY_PRODUCT_TYPE';
export const SET_IS_BIND_USER = 'SET_IS_BIND_USER';